### ISSUE TITLE
Global orientation and enu coordinate

### ISSUE THREAD

**Issue by airuchen** [HKUST-Aerial-Robotics/GVINS#10]
Hi,
I'm working on a gps navigation project and trying to use GVINS to realize localization. The issue I have is the transformation of the global orientation and the origin of the enu frame. Following are the more detailed questions:

1. By using 6-axis imu, gps and camera, how is the global orientation obtained?
2. How is enu origin defined? Is it the anchor mentioned in the paper? Is there any parameter like datum in the navsat_transform?

I also tried to fuse only /gvins/gnss_fused_lla to robot_localization's navsat_transform directly, but the result localization is drifting.

**Comment by shaozu** [comment]
1. The global pitch and roll can be obtained from the direction of gravity, and the global yaw is inferred from the local path and global path.
2. The origin of the ENU frame coincides with that of the local world frame. It is called anchor point in the paper. For datum, we use WGS84.
