### ISSUE TITLE
 how to buy the  vi-sensor nowadays

### ISSUE THREAD

**Issue by lhthq** [HKUST-Aerial-Robotics/GVINS#14]
hi~thank you  for your great  work! i want to  know how to buy the  vi-sensor nowadays? Or  could  you  recommend  a reliable  synchronized visual-inertial Sensor? Thanks!

**Comment by shaozu** [comment]
Hi, @lhthq. Sorry for the late replay.

Unfortunately the VI-Sensor is no longer available nowadays. However, you can try Intel's realsense D455 which is also a nice all-in-one suit with visual-inertial synced.
