### ISSUE TITLE
How to do Simulation

### ISSUE THREAD

**Issue by Kranthi18reddy** [HKUST-Aerial-Robotics/GVINS#15]
Hello, 

Thank you for great research. If I want to get same simulation results, how shall I generate data?
please share test generation package and if any procedure.

Regards,
Kranthi

**Comment by shaozu** [comment]
Hi, @Kranthi18reddy. To generate the simulation data, you need to design a path which the platform will follow and a 3D environment with sparse features. The IMU measurement can be obtained from the continuous path with noise and bias added. 
The visual measurement comes from the re-projection process of the 3D landmarks, again with Gaussian noise. For GNSS raw measurement, you need to calculate the position, velocity and time profile of navigation satellites iteratively and then measure the pseudorange and other quantities.
