### ISSUE TITLE
gnss_comm package not found 

### ISSUE THREAD

**Issue by arenas7307979** [HKUST-Aerial-Robotics/GVINS#2]
GNSS_COMM Links seem broken, Hope you can provide a new link
Thanks for sharing! That's an awesome work

**Comment by shaozu** [comment]
Hi @arenas7307979, thanks for your interests. I will fix it ASAP.

**Comment by shaozu** [comment]
Fixed.

**Comment by csunking** [comment]
git submodule add -b main --force https://github.com/HKUST-Aerial-Robotics/gnss_comm.git gnss_comm/

**Comment by csunking** [comment]
run the following script at GVINS root: 
git submodule add -b main --force https://github.com/HKUST-Aerial-Robotics/gnss_comm.git gnss_comm/
