### ISSUE TITLE
unit2rcv_pos in code

### ISSUE THREAD

**Issue by dean1314** [HKUST-Aerial-Robotics/GVINS#22]
Hello
I find you use dopp to constrain the position in code as follow
Eigen::Matrix3d unit2rcv_pos;
for (size_t i = 0; i < 3; ++i)
{
    for (size_t j = 0; j < 3; ++j)
    {
        if (i == j)
            unit2rcv_pos(i, j) = (norm2-rcv2sat_ecef(i)*rcv2sat_ecef(i))/norm3;
        else
            unit2rcv_pos(i, j) = (-rcv2sat_ecef(i)*rcv2sat_ecef(j))/norm3;
    }
}
but this method don't mention in your paper, so can you give me some papers about this method

**Comment by shaozu** [comment]
Hi, @dean1314. the term `unit2rcv_pos` is a part of the jacobian of the Doppler residual with respect to the receiver's position. It does not involve any special method but just plain derivatives. In fact, that term is very small, and you can safely ignore it.

**Comment by dean1314** [comment]
Thanks
but i don't see any receiver's position in the Doppler residual formula, the Doppler residual formula as follow
![image](https://user-images.githubusercontent.com/16264780/146107595-f0784a2d-76f2-46cd-9a4e-3753c7e9f053.png)

**Comment by shaozu** [comment]
It's in the directional vector \kappa.
