### ISSUE TITLE
How to dispaly the maps

### ISSUE THREAD

**Issue by Abner0907** [HKUST-Aerial-Robotics/GVINS#23]
@shaozu  Hello, I am very like this project. it is my needed. I have run it in my pc. all works good. Thank you very much for you nice work.

I have a simple question:
I want know how to display this path trajectory/path in the maps as yours.what tools should i use. how to configure it?  I am very appreciate that you can give some reference. thank you very much again. I can display the path in rviz without any map backgrounds.
![Screenshot from 2021-12-14 15-34-57](https://user-images.githubusercontent.com/64906552/145953245-3af83989-7fb3-452f-abf6-3955d5273eaf.png)

**Comment by shaozu** [comment]
Hi, @Abner0907. I used the javascript API provided by Google Maps, and you may want to refer [this page](https://developers.google.com/maps/documentation/javascript/overview) for some instructions.

**Comment by Abner0907** [comment]
@shaozu  Thank you very much, I will have a try now.

**Comment by Abner0907** [comment]
closed as now issues now
