### ISSUE TITLE
Question about the "uura" in gnss_psr_dopp_factor.cpp

### ISSUE THREAD

**Issue by bryantaoli** [HKUST-Aerial-Robotics/GVINS#27]
![3665c7fb8b41bd9d081fbbd3f6fdc76](https://user-images.githubusercontent.com/30526360/146661953-bc36cf56-15cb-4906-bb96-95002fe72492.png)
What does "uura" stand for and why is it calculated like this？
Thank you.

**Comment by shaozu** [comment]
The `uura` has no special meaning and it is just a part of the information weight associated with this factor. 
The information weight itself is an empirical formula as we verified in a long-term static receiver experiment.

**Comment by bryantaoli** [comment]
![image](https://user-images.githubusercontent.com/30526360/154441641-89b6917d-4529-4825-ba68-204ab3a09afd.png)
In your GVINS' paper, you said the clock jumps were avoided or carefully handled. But in your code, I cannot find anything about handling clock jump, could you please tell me how to  avoid or handle clock jumps in GVINS, thank you so much！
