### ISSUE TITLE
The program stuck at init 

### ISSUE THREAD

**Issue by Moreland-cas** [HKUST-Aerial-Robotics/GVINS#37]
Great works, thanks!
I notice that my own dataset do not have an /extermal_trigger topic? Can you please tell me how should I get one?

**Comment by SSZ1** [comment]
> Great works, thanks! I notice that my own dataset do not have an /extermal_trigger topic? Can you please tell me how should I get one?

Hi~Bro I have met the same problem as you. So have you solved it ? How did you solve this problem ?  Thanks for you patience.

**Comment by itzikcyberbee** [comment]
anyone figured this out and can help?

**Comment by Moreland-cas** [comment]
Not fixed

**Comment by itzikcyberbee** [comment]
ok... thanks
