### ISSUE TITLE
run visensor_f9p failed 

### ISSUE THREAD

**Issue by sheikhtar** [HKUST-Aerial-Robotics/GVINS#7]
Hello, after doing all the necessary steps and building the GVINS package, I couldn't run the visensor_f9p.launch    
Here is  the error that appears after typing the command roslaunch gvins visensor_f9p.launch
Can you help me resolving this issue please ?

auto-starting new master
process[master]: started with pid [8057]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 15004520-c541-11eb-88d2-1867b0884fc9
process[rosout-1]: started with pid [8073]
started core service [/rosout]
process[gvins_feature_tracker-2]: started with pid [8079]
process[gvins-3]: started with pid [8081]
[ INFO] [1622816889.314049540]: Loaded config_file: /home/elloumi/catkin_ws/src/GVINS/estimator/../config/visensor_f9p/visensor_left_f9p_config.yaml
result path /home/elloumi/output/vins_result_no_loop.csv
[ INFO] [1622816889.317172267]: ROW: 480.000000 COL: 752.000000 
[ WARN] [1622816889.317230606]:  fix extrinsic param 
[ INFO] [1622816889.317727824]: Extrinsic_R : 
   0.999989 -0.00432278  0.00179891
 0.00432766    0.999987 -0.00271802
-0.00178714  0.00272578    0.999995
[ INFO] [1622816889.317806542]: Extrinsic_T : 
 -0.0759473 -0.00393205  -0.0016395
[ INFO] [1622816889.317862017]: Synchronized sensors, fix time offset: 0
[ INFO] [1622816889.317960120]: GNSS enabled
[ INFO] [1622816889.318039380]: init begins
[ERROR] [1622816889.425234220]: Failed to load vins_folder

**Comment by shaozu** [comment]
Hi, @sheikhtar. The issue has been fixed. Please check out the latest commit.
