### ISSUE TITLE
Can GPS message format: gps_common/GPSFix or sensor_msgs/NavSatFix be used in this code?

### ISSUE THREAD

**Issue by llu0120** [HKUST-Aerial-Robotics/GVINS#9]
Hi, 
Really appreciate the work from you guys. I'm currently finding the orientation of my map between the gps pose and is interested in the intiailization step in this project proposed.  I'm wondering if I have gps message like `gps_common/GPSFix` and `sensor_msgs/NavSatFix` with longitude, latitude and altitude available already, how can we use this in the initialization step? Can you guys give me some idea or suggestions? Thank you in advance!

**Comment by shaozu** [comment]
Hi, @llu0120. If you already have a reliable GPS solution and local poses, you can use the `global_fusion` module of the [VINS-Fusion package](https://github.com/HKUST-Aerial-Robotics/VINS-Fusion) to find the alignment.
